### ISSUE TITLE
any plan adding requirements.txt?

### ISSUE THREAD

**Issue by katsu1110** [mrkmakr/bybit-bot#2]
Hey,

I found your work interesting. Good job. It seems that you use some modules which are not common (like pybybit). Would you mind sharing your requirements.txt? Thanks in advance:)

**Comment by mrkmakr** [comment]
I don't know how to make requirements.txt.
Would you give me some hints?

**Comment by katsu1110** [comment]
```
pip freeze > requirements.txt
```

should do.

**Comment by mrkmakr** [comment]
Thanks.
But it outputs requirements.txt including unnecessary libraries.
pipreqs is a smarter way to make requirements.txt.
I have added in this commit.
https://github.com/mrkmakr/bybit-bot/commit/ffc910dce9352d863a409f7f6eb41386d8c2da7a
